### ISSUE TITLE
General Roadmap

### ISSUE THREAD

**Issue by Staneesh** [Staneesh/optionator#1]
# `Optionator` 
Here is a roadmap aggregating all tasks, grouping and tracking them accordingly 🚀 

## Organization of Work
Tasks consisting of multiple tasks are **epic tasks** and are **bold** in the below hierarchy of tasks. They can be closed if and only if their sub-tasks are complete. If a task is non-trivial *or* involved implementation work, we should convert a task to issue. We don't need to convert epic tasks to issues, they are simply tracking progress on sub-tasks and don't represent any value added.

### Development
Branch `main` is considered to be the master branch. **Direct pushes to this branch are prohibited.** Developers self-impose a code review requirement on every pull request. Pull requests become stale when other PRs are merged onto the `main` branch and need to be re-based.   

# Tasks
The list of all tasks is included below. Epic tasks contain multiple sub-tasks.

## Repository Maintenance
- [X] Create a branch protection rule to prevent unreviewed pushed to the main branch.
- [X] Create a tracking issue for organizing and planning future work.
- [ ] Update `README.md` to summarize our work division, planning and organization. Link back to this master issue. 
## Implementation
- [ ] **Implement a Minimal Viable Product (MVP)**
  - [ ] Create a class representing an *option*.
